"""signup page locators"""

from selenium.webdriver.common.by import By

signup_page_header = (By.XPATH, "//form[@action='/signup']//preceding-sibling::h2")
mr_radio_btn = (By.ID, "id_gender1")
signup_name_field = (By.ID, "name")
signup_email_field = (By.ID, "email")
signup_password_field = (By.ID, "password")
day_of_birth_dropdown = (By.ID, "days")
month_of_birth_dropdown = (By.ID, "months")
year_of_birth_dropdown = (By.ID, "years")
newsletter_checkbox = (By.ID, "newsletter")
special_offers_checkbox = (By.ID, "optin")
first_name_field = (By.ID, "first_name")
last_name_field = (By.ID, "last_name")
company_name_field = (By.ID, "company")
address_1_field = (By.ID, "address1")
address_2_field = (By.ID, "address2")
country_dropdown = (By.ID, "country")
state_field = (By.ID, "state")
city_field = (By.ID, "city")
zipcode_field = (By.ID, "zipcode")
mobile_number_field = (By.ID, "mobile_number")
create_account_btn = (By.XPATH, "//button[@data-qa='create-account']")
account_created_header = (By.XPATH, "//h2//b[contains(text(),'Account Created!')]")
account_created_message = (By.XPATH, "//p[contains(text(),'Congratulations!')]")
continue_btn = (By.XPATH, "//a[contains(text(),'Continue')]")
